# Generated by Django 5.0.6 on 2024-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imageUrl',
            field=models.URLField(default='', max_length=500),
        ),
    ]
