# Generated by Django 5.0.6 on 2024-06-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ratings',
        ),
    ]
